### PR TITLE
Added Compadre package md file into pages/packages/mpi_x.

### PR DESCRIPTION
**Pull request by kuberry**
Created a page for the Compadre package, which was recently added into Trilinos.

### CODE REVIEW

**Comment by kuberry** [comment]
Hi, I've not added one of these before, and it isn't clear how I would transform the .md files into .html to check my work.

**Comment by jmgate** [comment]
I'm afraid I've never done anything with the github.io site.  Reassigning to @jwillenbring.

**Comment by mperego** [comment]
@kuberry Hi Paul, thanks for doing this. I'm actually doing some work on my for for all the packages in the discretization product. I'll create a PR soon so that you will be able to contribute. (and I'll copy this change). So please wait for it. Thanks!

**Comment by ccober6** [comment]
I needed to completely add Tempus.  Here is what I have so far https://github.com/trilinos/trilinos.github.io/pull/37.

**Comment by mperego** [comment]
> 
> 
> I needed to completely add Tempus. Here is what I have so far #37.

Thanks, yeah, I'm doing that for all the packages in the discretization pruduct.

**Comment by ccober6** [comment]
Let me know if you run into any gotchas that could avoid!

**Comment by mperego** [comment]
> 
> 
> Let me know if you run into any gotchas that could avoid!

Sure. I'm actually fighting with resizing images now!
B.t.w. where is this linked? `tempus_doxygen.md`

**Comment by ccober6** [comment]
Not sure.  @jwillenbring said I did not need to touch `tempus_doxygen.md`, so it might auto-generated?

**Comment by maherou** [comment]
Merge worked.  Submitted files (markdown, yaml) are automatically compiled by Github Pages Jekyll backend. to render html.  All is good.

**Comment by mperego** [comment]
> 
> 
> Merge worked. Submitted files (markdown, yaml) are automatically compiled by Github Pages Jekyll backend. to render html. All is good.

Yeah, I asked Paul not to merge just to avoid possible conflicts with what I was working on (PR #38), which included his patch. Anyway, even if we have conflicts, they will be easy to fix!

**Comment by maherou** [comment]
No problem doing things this way.  It is great to have all these contributions to the website.

**Pull request merged**
