### PR TITLE
Work related to Discretization Product

### PR DESCRIPTION
**Pull request by mperego**
I've updated the Discretization Product and the related packages.
Thanks @maherou and @jwillenbring for working on the framework and writing a first draft of them.
Thanks also for those who sent me some content.
@rppawlo @kyungjoo-kim @CamelliaDPG @alanw0 @lxmota @kuberry, feel free to make changes, in particular related to  the packages you develop.

Thanks!

### CODE REVIEW

**Comment by mperego** [comment]
You can see how it looks here
https://mperego.github.io/trilinos.github.io/index.html

**Comment by alanw0** [comment]
This looks good, it will be nice to have some improved documentation pages like this. I'm not clear on the terms 'Global Tools' 'Local Tools' and 'Shared Tools'.
I'm not sure which of those categories would be appropriate, but perhaps I could add a section about STK under one of them?

**Comment by maherou** [comment]
@alanw0 It would be great to have STK documentation.  I am not sure of the the categories, but @mperego should be able to provide guidance.

**Comment by mperego** [comment]
@alanw0 I think STK belongs to the data services product (@kddevin), not to then discretization one.

**Pull request merged**
